# Generated by Django 3.1.3 on 2020-12-06 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20201203_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizanswer',
            old_name='answer',
            new_name='answer_text',
        ),
    ]
