# Generated by Django 3.1.3 on 2020-12-06 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0008_auto_20201206_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.quizanswer'),
        ),
        migrations.AlterField(
            model_name='record',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='record',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='record',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.quiz'),
        ),
    ]
