# Generated by Django 3.1.3 on 2020-12-06 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20201206_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.quizanswer'),
        ),
        migrations.AlterField(
            model_name='record',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.question'),
        ),
    ]
